# Commands for aws cli:
# Validate script - aws cloudformation validate-template --template-body file://template.yaml
# Create stack - aws cloudformation create-stack --stack-name testname --template-body file://template.yaml
# View created stack status - aws cloudformation describe-stacks --stack-name testname
# Delete stack - aws cloudformation delete-stack --stack-name testname

Description: Test template for weer 0

Parameters:
  KeyName:
    Description: EC2 Instance SSH Key
    Type: AWS::EC2::KeyPair::KeyName
    Default: default-ssh-key

  EC2InstanceType:
    Description: EC2 instance type config
    Type: String
    Default: t2.micro

  EC2InstanceAmiId:
    Description: AMI ID for EC2
    Type: String
    Default: ami-026b57f3c383c2eec

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref EC2InstanceAmiId
      InstanceType: !Ref EC2InstanceType
      SecurityGroups:
        - !Ref SSHGroup
        - !Ref HTTPGroup

  SSHGroup:
    Description: ssh access group
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  HTTPGroup:
    Description: http access group
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  PublicIp:
    Description: EC2 Instance Public IP
    Value: !GetAtt EC2Instance.PublicIp